### PR TITLE
"Get messages" fixes: ackmode and redelivery flag 

### LINKED ISSUE #331: Request parameter ack_mode is named ackmode in RabbitMQ 3.9
Did it change name? Support both?

### PR DESCRIPTION
**Pull request by snichme**
Fixes #331

### CODE REVIEW

**Review by carlhoerberg — APPROVED** [review]

**Comment by jage** [comment]
Is this tested? (i.e. Ruby/Go HTTP API specs) Maybe something should be uncommented there.

**Comment by snichme** [comment]
https://github.com/cloudamqp/avalanchemq/pull/347/commits/67a1109d0a9849d265c653435c42fd8565149692 is to fix #270

**Comment by snichme** [comment]
Will revert the CI change if it passes

**Comment by carlhoerberg** [comment]
include `static/**` in paths instead?

**Comment by snichme** [comment]
I was just to quick, the http api was tested on commit https://github.com/cloudamqp/avalanchemq/pull/347/commits/b8a26df9bfecbc9691954d245027b7703c957498 which actually change (addition) to the api. 
The second commit is only changes to static, and then no need to run any tests since we have no tests or checks there.

**Pull request merged**
