### PR TITLE
Close Queue if an unrecoverable ReadError is raised

### PR DESCRIPTION
**Pull request by jage**
Otherwise the read/expire loop will just continue to loop.

### CODE REVIEW

**Comment by jage** [comment]
TODO:

* [ ] How should `Exchange` handle a closed `Queue`?
* [ ] Consider adding a few more specs,  i.e. break it in other ways
* [ ] Fix default_user spec having side-effects

**Comment by carlhoerberg** [comment]
Maybe distinguish between Segment file read error and Index read error?

**Comment by jage** [comment]
> Maybe distinguish between Segment file read error and Index read error?

I think many cases are hard to distinguish, i.e. is it corrupt data in mfile or reading from wrong position, so most will probably be IndexError. But IO errors from the mfile could be marked as as Segment errors.

**Comment by jage** [comment]
> * [x]  How should `Exchange` handle a closed `Queue`

We will handle it as deleted queues, just skip. nack on closed/errored queues will be a future improvement.

**Review by snichme — APPROVED** [review]

**Pull request merged**
