### PR TITLE
Replace Logger framework with Log from stdlib

### LINKED ISSUE #302: Log level reload does not change all loggers
Reproduce by starting with `log_level = debug`, change to `info` and reload, wait for debug output.

```ini
[main]
log_level = debug # Change to info, then pkill -HUP avalanchemq to reload
data_dir = /tmp/log_example
```

```
$ bin/avalanchemq -c /tmp/amq.conf
2021-11-01 12:00:19 +01:00 [INFO] : AvalancheMQ 1.0.0-alpha.33
Crystal 1.2.1 (2021-10-21)
LLVM: 11.1.0
Default target: x86_64-apple-macosx
Build flags: --release --debug
2021-11-01 12:00:19 +01:00 [INFO] : Pid: 8808
2021-11-01 12:00:19 +01:00 [INFO] : Config file: /tmp/amq.conf
2021-11-01 12:00:19 +01:00 [INFO] : Data directory: /tmp/log_example
2021-11-01 12:00:19 +01:00 [INFO] : FD limit: 5568
2021-11-01 12:00:19 +01:00 [DEBUG] amqpserver: Loading users from file
2021-11-01 12:00:19 +01:00 [DEBUG] amqpserver: 2 users loaded
2021-11-01 12:00:19 +01:00 [DEBUG] amqpserver: Loading vhosts from file
2021-11-01 12:00:19 +01:00 [DEBUG] vhost=/: 0 items loaded from policies.json
2021-11-01 12:00:19 +01:00 [DEBUG] vhost=/: 0 items loaded from parameters.json
2021-11-01 12:00:19 +01:00 [INFO] amqpserver: Updated permissions to vhost=/ for user=__direct
2021-11-01 12:00:19 +01:00 [DEBUG] amqpserver: Saving users to file
2021-11-01 12:00:19 +01:00 [DEBUG] amqpserver: 1 vhosts loaded
2021-11-01 12:00:19 +01:00 [DEBUG] amqpserver: 0 items loaded from parameters.json
2021-11-01 12:00:19 +01:00 [INFO] httpserver: Bound to 127.0.0.1:15672
2021-11-01 12:00:19 +01:00 [INFO] httpserver: Bound to /tmp/avalanchemq-http.sock
2021-11-01 12:00:19 +01:00 [INFO] amqpserver: Listening on 127.0.0.1:5672
2021-11-01 12:00:25 +01:00 [INFO] : Reloading configuration file '/tmp/amq.conf'
2021-11-01 12:00:25 +01:00 [INFO] : Log level changed from DEBUG to INFO
2021-11-01 12:00:38 +01:00 [INFO] vhost=/: GC segments, collecting sps used 0B memory
2021-11-01 12:00:38 +01:00 [DEBUG] vhost=/: GC segments # !!! Should NOT be logged
2021-11-01 12:00:38 +01:00 [INFO] vhost=/: GC segments, garbage collecting used 0B memory
2021-11-01 12:00:38 +01:00 [INFO] vhost=/: GC segments, compact internal queues used 0B memory
2021-11-01 12:00:38 +01:00 [INFO] vhost=/: GC segments, GC collect used 0B memory
```

We do `log.dup` when passing logger around, probably need to rethink this or how we change the level.

### PR DESCRIPTION
**Pull request by snichme**
Make use of the new log module included in Crystal

Support different formatters,  exceptions and metadata where you can add additional data to the logger, preview below (second WARN)

Log output: 
```
2022-03-21T12:57:17.387659Z DEBUG httpserver.QueuesController list_queue
2022-03-21T12:57:17.387667Z  INFO httpserver.QueuesController list_queue
2022-03-21T12:57:17.387670Z  WARN httpserver.QueuesController list_queue
2022-03-21T12:57:17.387675Z  WARN httpserver.QueuesController log_queues -- length: 10
2022-03-21T12:57:17.387678Z ERROR httpserver.QueuesController list_queue
2022-03-21T12:57:17.387681Z ERROR httpserver.QueuesController list_queue
aaa (AvalancheMQ::Error)
``` 

Fixes #302

### CODE REVIEW

**Comment by snichme** [comment]
We use the "source" for each log entry differently which makes it hard to format in a good way. 

For example 
An http controller uses `http.QueuesController` as source
but a queue used `vhost=/ queue=q_name`

I would like not to use spaces in the source since it makes it harder to filter logs using `awk` and other tools since the source could contains various amount of spaces.  

For the queue logs one idea is to change from 
`DEBUG vhost=/¤queue=asdsadsada Waiting for msgs`
to
`DEBUG Queue Waiting for msgs -- vhost=/ queue=asdsadsada ` 
which makes use of the data field this logger has

**Comment by snichme** [comment]
Output style: 
```
2022-03-22T11:02:39.563402Z DEBUG userstore Loading users from file
2022-03-22T11:02:39.564302Z DEBUG userstore 2 users loaded
2022-03-22T11:02:39.564362Z DEBUG vhoststore Loading vhosts from file
2022-03-22T11:02:39.565082Z DEBUG vhost{name:/} 0 items loaded from policies.json
2022-03-22T11:02:39.565102Z DEBUG vhost{name:/} 0 items loaded from parameters.json
2022-03-22T11:02:39.565980Z DEBUG queue{vhost:/ name:asdsadsada} Index dir: ./ca1/42099b4af021e53fd8fd4e056c2568d7c2e3ffa8/3dd46851afaaad437a69e59ba086b1a119bef6e0
2022-03-22T11:02:39.565993Z  INFO queue{vhost:/ name:asdsadsada} Restoring index
2022-03-22T11:02:39.566186Z  INFO queue{vhost:/ name:asdsadsada} 0 messages
2022-03-22T11:02:39.567638Z  INFO userstore Updated permissions to vhost=/ for user=__direct
2022-03-22T11:02:39.567643Z DEBUG userstore Saving users to file
2022-03-22T11:02:39.568771Z DEBUG vhoststore 1 vhosts loaded
2022-03-22T11:02:39.568790Z DEBUG amqpserver 0 items loaded from parameters.json
2022-03-22T11:02:39.570012Z  INFO http Bound to 127.0.0.1:15672
2022-03-22T11:02:39.570068Z  INFO http Bound to /dev/shm/avalanchemq-http.sock
2022-03-22T11:02:39.572060Z DEBUG queue{vhost:/ name:asdsadsada} Waiting for msgs
2022-03-22T11:02:39.572193Z  INFO amqpserver Listening on 127.0.0.1:5672
```

**Comment by carlhoerberg** [comment]
Most of the time we output to journald, and don't need/want to output the timestamp. I think we have code that identifies that today, it's a env variable set

**Comment by jage** [comment]
> Most of the time we output to journald, and don't need/want to output the timestamp. I think we have code that identifies that today, it's a env variable set

https://github.com/cloudamqp/avalanchemq/blob/fe01fa1a91aeb9b701c922cdaa2b09c0a5e14c1c/src/avalanchemq/log_formatter.cr#L19

**Comment by carlhoerberg** [comment]
Some double logging: 
```
2022-03-22T14:56:52.542459Z  INFO client{vhost:/ client:127.0.0.1:51572 } Connection (127.0.0.1:51572 -> 127.0.0.1:5672) established for user=guest
```

**Comment by carlhoerberg** [comment]
and `client` has a space before `}`. but otherwise it looks very good at glance!

**Review by carlhoerberg — APPROVED** [review]

**Comment by carlhoerberg** [comment]
Changed the output somewhat, : to = and {} to [].

```
2022-03-22T21:59:45.184104Z  INFO queue[vhost=/ name=perf-test] Restoring index
2022-03-22T21:59:45.184240Z  INFO queue[vhost=/ name=perf-test] 0 messages
2022-03-22T21:59:45.184380Z  INFO userstore Updated permissions to vhost=/ for user=__direct
2022-03-22T21:59:45.190734Z  INFO http Bound to 127.0.0.1:15672
2022-03-22T21:59:45.190774Z  INFO http Bound to /dev/shm/avalanchemq-http.sock
2022-03-22T21:59:45.191834Z  INFO amqpserver Listening on 127.0.0.1:5672
2022-03-22T21:59:45.191875Z  INFO amqpserver Listening on 127.0.0.1:5671 (TLS)
2022-03-22T21:59:49.192451Z  INFO vhost[name=/] GC segments, collecting sps used 0B memory
2022-03-22T21:59:49.192488Z  INFO vhost[name=/] GC segments, garbage collecting used 0B memory
2022-03-22T21:59:49.192500Z  INFO vhost[name=/] GC segments, compact internal queues used 0B memory
2022-03-22T21:59:49.193220Z  INFO vhost[name=/] GC segments, GC collect used 0B memory
2022-03-22T21:59:50.083949Z  INFO client[vhost=/ address=127.0.0.1:51606] Connection established for user=guest
2022-03-22T21:59:50.084083Z  INFO client[vhost=/ address=127.0.0.1:51608] Connection established for user=guest
2022-03-22T21:59:52.416973Z  INFO client[vhost=/ address=127.0.0.1:51608] Connection disconnected for user=guest
2022-03-22T21:59:52.417253Z  INFO client[vhost=/ address=127.0.0.1:51606] Connection disconnected for user=guest
```

Feel free to revert if you hate it

**Pull request merged**
